/* QiblaAstro — Prayer schedule location + authenticated Android sync. */
(function(root){
'use strict';
/* Migration guard: app.qiblalabs.com can be served to both versionCode 3 and
 * versionCode 5 during the closed-test rollout. Code 3 does not understand the
 * widgetOnly query field, so an independent widget refresh could mutate its
 * native Adhan state. Keep independent widget-only handoff disabled until Code 3
 * is retired. Widget data still refreshes through an already-authorized prayer
 * sync, which carries the user's real Adhan choices. */
var LEGACY_CODE3_MIGRATION_GUARD=true;
/* An intent:// handoff changes Android task focus. Never launch it from startup,
 * polling, focus, visibility or passive location/runtime events. Native prayer
 * delivery is armed only by an explicit user action; the Android AlarmManager
 * then owns closed-app/offline delivery without further Web navigation. */
var AUTO_NATIVE_NAVIGATION=false;
var lastKey='',timer=0,TOKEN_KEY='qiblaastro:native-token',AUTO_KEY='qiblaastro:prayer-native-sync-enabled:v1',WIDGET_AUTO_KEY='qiblaastro:widget-native-sync-enabled:v1',LAST_SYNC_KEY='qiblaastro:prayer-native-sync-last:v1';
function hashParams(hash){var raw=String(hash||'').replace(/^#/,'');var params=new URLSearchParams(raw);if(params.has('nativeToken'))return params;try{var decoded=decodeURIComponent(raw);if(decoded!==raw){var legacy=new URLSearchParams(decoded);if(legacy.has('nativeToken'))return legacy;}}catch(_){}return params;}
function captureToken(){try{var hp=hashParams(root.location.hash),t=hp.get('nativeToken');if(t&&t.length>=32){root.sessionStorage.setItem(TOKEN_KEY,t);hp.delete('nativeToken');var cleanHash=hp.toString();root.history.replaceState(null,'',root.location.pathname+root.location.search+(cleanHash?'#'+cleanHash:''));return t;}return root.sessionStorage.getItem(TOKEN_KEY)||'';}catch(_){return '';}}
function ensurePlanModule(){try{if(root.QiblaPrayerNativePlan)return true;if(!root.document)return false;if(root.document.querySelector('script[data-qibla-prayer-native-plan]'))return false;var s=root.document.createElement('script');s.src='js/presentation/prayer/native-plan.js?v=20260827-authoritative1';s.async=false;s.setAttribute('data-qibla-prayer-native-plan','true');(root.document.head||root.document.documentElement).appendChild(s);}catch(_){}return false;}
function currentKey(){try{if(!Number.isFinite(Number(LAT))||!Number.isFinite(Number(LON)))return '';var src=typeof gnssSource!=='undefined'?String(gnssSource):'unknown';return Number(LAT).toFixed(3)+','+Number(LON).toFixed(3)+'|'+src;}catch(e){return '';}}
function invalidateIfNeeded(){var key=currentKey();if(!key)return;if(!lastKey){lastKey=key;maybeNativeSync('location-ready');return;}if(key===lastKey)return;lastKey=key;try{if(typeof pKey!=='undefined')pKey='';}catch(e){}try{if(root.QiblaPrayerScreen&&typeof root.QiblaPrayerScreen.render==='function')root.QiblaPrayerScreen.render();}catch(e){}try{root.dispatchEvent(new CustomEvent('qiblaastro:prayer-location-changed',{detail:{key:key}}));}catch(e){}root.setTimeout(function(){maybeNativeSync('location-changed');},250);}
function prayerSchedule(){try{var runtime=root.QiblaTrustedLocationRuntimeSync;if(runtime&&typeof runtime.getSchedule==='function'){var schedule=runtime.getSchedule();return Array.isArray(schedule)&&schedule.length?schedule:null;}return(typeof pCache!=='undefined'&&Array.isArray(pCache))?pCache:null;}catch(_){return null;}}
function minuteFor(name){try{var schedule=prayerSchedule(),p=schedule?schedule.find(function(x){return x&&x.n===name;}):null;if(!p||!Number.isFinite(Number(p.h)))return -1;return ((Math.round(Number(p.h)*60)%1440)+1440)%1440;}catch(_){return -1;}}
function cleanWidgetText(value){return String(value||'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim();}
function widgetMinute(value){value=Number(value);if(!Number.isFinite(value)||value<0||value>=1440)return'--:--';var h=Math.floor(value/60),m=Math.floor(value%60);return(h<10?'0':'')+h+':'+(m<10?'0':'')+m;}
function widgetGregorianDate(timeZone){try{return cleanWidgetText(new Intl.DateTimeFormat('ar-EG-u-nu-latn',{weekday:'short',day:'numeric',month:'short',timeZone:timeZone||undefined}).format(new Date()).replace(/،/g,''));}catch(_){return'';}}
function widgetLocationLabel(loc){var values=[];if(loc&&loc.mode==='manual')values.push(loc.label);try{var api=root.QiblaLocationLabel;if(api&&typeof api.getLabel==='function')values.push(api.getLabel());}catch(_){}try{var el=root.document&&root.document.getElementById('prayer-location-label');if(el)values.push(el.textContent);}catch(_){}values.push(loc&&loc.label);for(var i=0;i<values.length;i++){var s=cleanWidgetText(values[i]);if(!s||s==='الموقع الافتراضي'||s==='GPS'||s==='موقعك الحالي'||s.indexOf('موقعك الحالي ·')===0)continue;return s.split(/[،,]/)[0].trim().slice(0,32);}return cleanWidgetText(loc&&loc.label||'موقعك الحالي').replace(/\s*·\s*GPS$/,'').slice(0,32);}
function widgetHijriShort(value){return cleanWidgetText(value).replace(/\s*هـ\s*$/,'').trim();}
function widgetPrayerRow(name,value){return '\u200F'+name+' \u200E'+widgetMinute(value);}
function widgetPresentation(payload,hijriOverride){payload=payload||{};var loc=payload.loc||{},times=payload.times||{},hijri='';if(hijriOverride!==undefined&&hijriOverride!==null)hijri=cleanWidgetText(hijriOverride);else try{var h=root.document&&root.document.getElementById('pr-h');hijri=cleanWidgetText(h&&h.textContent?h.textContent:'');}catch(_){}var tz=payload.plan&&payload.plan.timeZone||loc.timeZone||'',city=widgetLocationLabel(loc),gregorian=widgetGregorianDate(tz),dateLine=[city,gregorian,widgetHijriShort(hijri)].filter(Boolean).join(' • ');if(dateLine.length>64)dateLine=dateLine.slice(0,64).replace(/[•·\s]+$/,'');var rows=[widgetPrayerRow('الفجر',times.fajr),widgetPrayerRow('الظهر',times.dhuhr),widgetPrayerRow('العصر',times.asr),widgetPrayerRow('المغرب',times.maghrib),widgetPrayerRow('العشاء',times.isha)].join('\u2028');if(rows.length>80)throw new Error('Widget prayer rows exceed native safeText limit');return{city:dateLine,summary:rows};}
function hasExplicitPrayerPrefs(){try{return ['qiblaastro-adhan-ui-v5','qiblaastro-adhan-ui-v4','qiblaastro-adhan-ui-v3','qiblaastro-adhan-ui-v2','qiblaastro-adhan-ui-v1'].some(function(k){return !!root.localStorage.getItem(k);});}catch(_){return false;}}
function autoEnabled(){try{return root.localStorage.getItem(AUTO_KEY)==='1';}catch(_){return false;}}
function setAutoEnabled(){try{root.localStorage.setItem(AUTO_KEY,'1');}catch(_){ }}
function widgetAutoEnabled(){try{return root.localStorage.getItem(WIDGET_AUTO_KEY)==='1';}catch(_){return false;}}
function setWidgetAutoEnabled(){try{root.localStorage.setItem(WIDGET_AUTO_KEY,'1');}catch(_){ }}
function nativePayload(){var token=captureToken();if(!token)return null;ensurePlanModule();var loc=root.QiblaPrayerLocation&&root.QiblaPrayerLocation.effective?root.QiblaPrayerLocation.effective():null,st=root.QiblaAdhanUI&&root.QiblaAdhanUI.getState?root.QiblaAdhanUI.getState():null;if(!loc||!st||!root.QiblaPrayerNativePlan)return null;var map={fajr:'الفجر',dhuhr:'الظهر',asr:'العصر',maghrib:'المغرب',isha:'العشاء'},times={};for(var id in map){var minute=minuteFor(map[id]);if(minute<0)return null;times[id]=minute;}var plan=root.QiblaPrayerNativePlan.build(14),planText=root.QiblaPrayerNativePlan.serialize(plan);if(!plan||!planText)return null;return {token:token,loc:loc,st:st,times:times,map:map,plan:plan,planText:planText};}
function fingerprint(payload){try{var loc=payload.loc,st=payload.st,t=payload.times;return [payload.planText,currentKey(),loc.timeZone||'',st.enabled?'1':'0',String(st.advance||0),st.profile||'makkah',t.fajr,t.dhuhr,t.asr,t.maghrib,t.isha,payload.map.fajr+':'+((st.prayers&&st.prayers[payload.map.fajr])||'off'),payload.map.dhuhr+':'+((st.prayers&&st.prayers[payload.map.dhuhr])||'off'),payload.map.asr+':'+((st.prayers&&st.prayers[payload.map.asr])||'off'),payload.map.maghrib+':'+((st.prayers&&st.prayers[payload.map.maghrib])||'off'),payload.map.isha+':'+((st.prayers&&st.prayers[payload.map.isha])||'off')].join('|');}catch(_){return '';}}
function lastSync(){try{return root.sessionStorage.getItem(LAST_SYNC_KEY)||'';}catch(_){return '';}}
function markSync(key){try{root.sessionStorage.setItem(LAST_SYNC_KEY,key);}catch(_){ }}
function packageIntent(q){return 'intent://prayer-sync?'+q.toString()+'#Intent;scheme=qiblaastro;package=com.qiblalabs;category=android.intent.category.BROWSABLE;end';}
function launchBridge(q){var uri=packageIntent(q);try{var topWin=root.top||root;topWin.location.href=uri;return true;}catch(_){try{root.location.href=uri;return true;}catch(__){return false;}}}
function nativeSync(reason,widgetOnly){var payload=nativePayload();if(!payload)return false;var fp=fingerprint(payload)+(widgetOnly?'|widget-only':'|delivery');if(!fp)return false;if(reason!=='explicit'&&reason!=='widget'&&lastSync()===fp)return true;var token=payload.token,loc=payload.loc,st=payload.st,q=new URLSearchParams();q.set('token',token);q.set('notify',st.enabled?'1':'0');if(widgetOnly)q.set('widgetOnly','1');var widget=widgetPresentation(payload);q.set('city',widget.city);q.set('tz',payload.plan.timeZone||loc.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone||'');q.set('plan',payload.planText);q.set('hijri',widget.summary);try{if(Number.isFinite(Number(QT)))q.set('qibla',Number(QT).toFixed(1));}catch(_){}q.set('advance',String(st.advance||0));q.set('profile',st.profile||'makkah');Object.keys(payload.map).forEach(function(id){q.set('t_'+id,String(payload.times[id]));q.set('m_'+id,(st.prayers&&st.prayers[payload.map[id]])||'off');});var launched=launchBridge(q);if(launched){markSync(fp);if(reason==='explicit'&&!widgetOnly)setAutoEnabled();}return launched;}
function maybeAutoSync(reason){if(!AUTO_NATIVE_NAVIGATION)return false;if(!captureToken())return false;if(!autoEnabled()&&!hasExplicitPrayerPrefs())return false;return nativeSync(reason||'auto');}
function maybeWidgetSync(reason){if(LEGACY_CODE3_MIGRATION_GUARD)return false;if(!captureToken()||!widgetAutoEnabled())return false;if(autoEnabled()||hasExplicitPrayerPrefs())return false;return nativeSync(reason||'widget-auto',true);}
function maybeNativeSync(reason){return maybeAutoSync(reason)||maybeWidgetSync(reason);}
function explicitSync(){return nativeSync('explicit');}
function widgetSync(){
  if(LEGACY_CODE3_MIGRATION_GUARD){
    /* Never create an independent delivery state while Code 3 may still be
       installed. If prayer preferences were already explicitly authorized,
       a normal full sync is safe and refreshes the shared private widget store. */
    if(!captureToken()||(!autoEnabled()&&!hasExplicitPrayerPrefs()))return false;
    return nativeSync('widget-legacy-safe',false);
  }
  var launched=nativeSync('widget',true);if(launched)setWidgetAutoEnabled();return launched;
}
function syncWidgetControl(){try{var button=root.document&&root.document.querySelector('[data-qa-widget-sync]');if(button){var token=!!captureToken(),authorized=autoEnabled()||hasExplicitPrayerPrefs();button.hidden=!token||(LEGACY_CODE3_MIGRATION_GUARD&&!authorized);}}catch(_){}}
function start(){if(timer)return;captureToken();ensurePlanModule();syncWidgetControl();lastKey=currentKey();timer=root.setInterval(function(){invalidateIfNeeded();if(!root.document||!root.document.hidden)maybeNativeSync('poll');},1500);root.addEventListener('focus',function(){invalidateIfNeeded();maybeNativeSync('focus');});root.document&&root.document.addEventListener('visibilitychange',function(){if(!root.document.hidden){invalidateIfNeeded();maybeNativeSync('visible');}});root.addEventListener('qiblaastro:presentation-page-mounted',syncWidgetControl);root.addEventListener('qiblaastro:prayer-location-changed',function(){root.setTimeout(function(){maybeNativeSync('location-event');},250);});root.addEventListener('qiblaastro:prayer-runtime-sync',function(e){if(e&&e.detail&&e.detail.ok)root.setTimeout(function(){maybeNativeSync('runtime-ready');},100);});if(root.document)root.document.addEventListener('click',function(e){var widget=e.target&&e.target.closest?e.target.closest('[data-qa-widget-sync]'):null;if(widget){e.preventDefault();try{widgetSync();}catch(_){}return;}var t=e.target&&e.target.closest?e.target.closest('[data-city-id],[data-location-auto],[data-custom-save],[data-method],[data-asr],[data-high-lat],[data-profile],[data-advance],[data-prayer-mode],[data-qa-adhan-toggle]'):null;if(t){try{explicitSync();}catch(_){}}},false);root.setTimeout(function(){maybeNativeSync('startup');},800);}
root.QiblaPrayerNativeSync=Object.freeze({sync:explicitSync,syncWidget:widgetSync,refresh:maybeNativeSync,refreshWidget:maybeWidgetSync,captureToken:captureToken,widgetPreview:widgetPresentation});
root.QiblaPrayerScheduleSync=Object.freeze({start:start,check:invalidateIfNeeded});
if(root.document){if(root.document.readyState==='loading')root.document.addEventListener('DOMContentLoaded',start,{once:true});else start();}
})(typeof globalThis!=='undefined'?globalThis:window);
