'use strict';
const assert=require('assert');
const fs=require('fs');
const read=p=>fs.readFileSync(p,'utf8');
const bridge=read('js/azkar-native-reminders.js');
const html=read('pages/azkar.html');
const scheduler=read('android-twa/native/azkar-reminders/AzkarReminderScheduler.java');
assert(bridge.includes("SELECTION_KEY='qiblaastro:azkar-reminder-selection:v1'"),'Azkar UI selection persistence key missing');
assert(bridge.includes("STORAGE_KEY='qiblaastro:native-azkar-reminder:v1'"),'Native running-state key must remain unchanged');
assert(bridge.includes('function saveAudioSelection'),'Azkar selection save helper missing');
assert(bridge.includes('function readAudioSelection'),'Azkar selection restore helper missing');
assert(bridge.includes('applySelection(running)'),'Running Native reminder must restore its selected phrase and interval');
assert(html.includes('data-qibla-azkar-selection-sync'),'Current Code 5 page must contain cache-safe selection restoration');
assert(html.includes('لضمان عمل التذكير دون إنترنت والتطبيق مغلق'),'Offline/closed-app battery note missing');
assert(html.includes('على «لا قيود»'),'Battery note must name the required unrestricted setting');
assert(scheduler.includes('setAndAllowWhileIdle(AlarmManager.ELAPSED_REALTIME_WAKEUP'),'Native reminder scheduling must remain untouched');
console.log('Azkar selected phrase + interval persistence and battery note: PASS');
