'use strict';
const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const source=fs.readFileSync('js/presentation/prayer/schedule-sync.js','utf8');
assert(source.includes('function widgetPresentation(payload,hijriOverride)'),'widget formatter missing');
assert(source.includes("q.set('hijri',widget.summary)"),'native widget sync must receive prayer summary');
assert(!source.includes('widgetCountdown'),'Code 5 must not fake a stale live countdown');
function storage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
const context={console,URLSearchParams,Intl,Date,Number,Math,Object,Array,String,Promise,document:null,location:{hash:'',pathname:'/',search:''},history:{replaceState(){}},sessionStorage:storage(),localStorage:storage(),setInterval(){return 1;},setTimeout(){return 1;},addEventListener(){}};
context.globalThis=context;
vm.runInNewContext(source,context,{filename:'schedule-sync.js'});
assert(context.QiblaPrayerNativeSync&&typeof context.QiblaPrayerNativeSync.widgetPreview==='function','widget preview helper must be exported');
context.QiblaLocationLabel={getLabel:()=> 'الجيزة، مصر'};
const preview=context.QiblaPrayerNativeSync.widgetPreview({loc:{label:'موقعك الحالي',timeZone:'Africa/Cairo'},plan:{timeZone:'Africa/Cairo'},times:{fajr:299,dhuhr:777,asr:992,maghrib:1163,isha:1244}},'16 ربيع الأول 1448 هـ');
assert(preview.city.startsWith('الجيزة'),'resolved city must replace generic current-location label');
assert(!preview.city.includes('السبت'),'top line must remain compact');
assert(preview.city.length<=80,'native city safeText limit is 80 chars');
assert(preview.summary.length<=80,'native summary safeText limit is 80 chars');
for(const value of ['الفجر 4:59 ص','الظهر 12:57 م','العصر 4:32 م','المغرب 7:23 م','العشاء 8:44 م'])assert(preview.summary.includes(value),`missing clean 12-hour item ${value}`);
assert(!/[\u2028\u200e\u200f]/.test(preview.summary),'summary must not contain unsupported line/bidi glyphs');
assert(!/[فجظهعصمغعش]\d{1,2}:\d{2}/.test(preview.summary),'abbreviated prayer names must not return');
console.log('Code 5 widget: resolved city + compact dates + full prayer names + 12-hour times: PASS');
