'use strict';
const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const source=fs.readFileSync('js/presentation/prayer/schedule-sync.js','utf8');
assert(source.includes('function widgetPresentation(payload,hijriOverride)'),'widget formatter missing');
assert(source.includes("q.set('hijri',widget.summary)"),'native widget sync must receive prayer rows');
assert(!source.includes('widgetCountdown'),'Code 5 must not fake a stale live countdown');
function storage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
const context={console,URLSearchParams,Intl,Date,Number,Math,Object,Array,String,Promise,document:null,location:{hash:'',pathname:'/',search:''},history:{replaceState(){}},sessionStorage:storage(),localStorage:storage(),setInterval(){return 1;},setTimeout(){return 1;},addEventListener(){}};
context.globalThis=context;
vm.runInNewContext(source,context,{filename:'schedule-sync.js'});
assert(context.QiblaPrayerNativeSync&&typeof context.QiblaPrayerNativeSync.widgetPreview==='function','widget preview helper must be exported');
context.QiblaLocationLabel={getLabel:()=> 'القاهرة، مصر'};
const preview=context.QiblaPrayerNativeSync.widgetPreview({loc:{label:'موقعك الحالي',timeZone:'Africa/Cairo'},plan:{timeZone:'Africa/Cairo'},times:{fajr:299,dhuhr:777,asr:992,maghrib:1163,isha:1244}},'16 ربيع الأول 1448 هـ');
assert(preview.city.startsWith('القاهرة'),'resolved city must replace generic current-location label');
assert(preview.city.includes('ربيع'),'city/date line must preserve Hijri context');
assert(preview.city.length<=80,'native city safeText limit is 80 chars');
assert(preview.summary.length<=80,'native summary safeText limit is 80 chars');
for(const value of ['الفجر','الظهر','العصر','المغرب','العشاء','04:59','12:57','16:32','19:23','20:44'])assert(preview.summary.includes(value),`missing widget row value ${value}`);
assert.strictEqual((preview.summary.match(/\u2028/g)||[]).length,4,'five prayers must be separated into five explicit visual rows');
assert(!/[فجظهعصمغعش]\d{2}:\d{2}/.test(preview.summary),'abbreviated prayer names must not return');
console.log('Code 5 widget: resolved city/date line + five full-name prayer rows within native limits: PASS');
