'use strict';
const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const ui=read('js/presentation/prayer/adhan-ui.js');
const sync=read('js/presentation/prayer/schedule-sync.js');
const bootstrap=read('js/presentation/bootstrap.js');
const sw=read('service-worker.js');
const scheduler=read('android-twa/native/prayer-widget/PrayerNativeScheduler.java');
const receiver=read('android-twa/native/prayer-widget/PrayerNotificationReceiver.java');
const service=read('android-twa/native/prayer-widget/AdhanPlaybackService.java');

assert(ui.includes("function nativeDeliveryOwner()"),'Native/TWA delivery owner detector missing');
assert(ui.includes("sessionStorage.getItem('qiblaastro:twa')==='1'"),'TWA marker must select Native delivery');
assert(ui.includes("sessionStorage.getItem('qiblaastro:native-token')"),'Native delivery must require authenticated token');
assert(ui.includes("function checkSchedule(now,cache){if(nativeDeliveryOwner())return false;"),'Web scheduler must never deliver scheduled prayer events inside authenticated Android TWA');
assert(ui.includes("function startRuntimeScheduler(){if(nativeDeliveryOwner()){installSchedulerAdapter();return true;}"),'Android TWA must not start the one-second Web prayer delivery timer');
assert(ui.includes("if(nativeDeliveryOwner())return Promise.resolve('native');"),'Android TWA must use Native notification permission rather than Web notification prompt');
assert(ui.includes("result==='native'?'إشعارات Android هي المستخدمة داخل التطبيق'"),'Native permission ownership must be explained without a false browser-permission error');
assert(sync.includes('var AUTO_NATIVE_NAVIGATION=false;'),'Passive Web-to-Android intent navigation must remain disabled');
assert(sync.includes("function explicitSync(){return nativeSync('explicit');}"),'Explicit user settings must still arm Native prayer delivery');
assert(bootstrap.includes('adhan-ui.js?v=20260829-native-owner1'),'Bootstrap must request the Native-owner Adhan UI revision');
assert(bootstrap.includes('schedule-sync.js?v=20260829-widget-rich1'),'Bootstrap must request the foreground-stable rich-widget prayer sync revision');
assert(sw.includes("VERSION='qiblaastro-v5.74-native-adhan-owner-20260829'"),'Offline cache generation must advance for Native Adhan ownership');
assert(sw.includes("OFFLINE_RELEASE='native-adhan-owner-20260829'"),'Offline release marker must describe the new Adhan ownership contract');
assert(scheduler.includes('setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, at, pi)'),'Prayer time must remain exact when Android grants access');
assert(scheduler.includes('setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,backup)'),'Prayer time must retain idle-safe backup');
assert(receiver.includes('context.startForegroundService(service)'),'Closed-app alarm receiver must start Native playback service');
assert(service.includes('getResources().openRawResourceFd(rawId)'),'Adhan audio must remain bundled/local');
assert(service.includes('AudioAttributes.USAGE_ALARM'),'Native playback must use alarm audio semantics');
console.log('Code 5 Native Adhan ownership + offline/closed-app contract: PASS');
