'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=process.cwd(),sets=['values','values-en','values-fr','values-id','values-ur'];
function read(p){return fs.readFileSync(path.join(root,p),'utf8');}
function stringNames(xml){return new Set([...xml.matchAll(/<string\s+name="([^"]+)"/g)].map(m=>m[1]));}
const azkarRequired=['azkar_channel_name','azkar_channel_description','azkar_notification_title','azkar_start_title','azkar_start_message','azkar_start_action','azkar_stop_title','azkar_stop_message','azkar_stop_action','azkar_cancel_action','azkar_permission_required','azkar_started_toast'];
for(const set of sets){const p=`android-twa/native/azkar-reminders/res/${set}/strings.xml`;assert(fs.existsSync(p),`${p} missing`);const n=stringNames(read(p));for(const k of azkarRequired)assert(n.has(k),`${set} missing ${k}`);}
const activity=read('android-twa/native/azkar-reminders/AzkarReminderActivity.java');
const azScheduler=read('android-twa/native/azkar-reminders/AzkarReminderScheduler.java');
const azReceiver=read('android-twa/native/azkar-reminders/AzkarReminderReceiver.java');
assert(activity.includes('NativeBridgeToken.valid'),'Azkar native bridge must require per-install token');
assert(activity.includes('POST_NOTIFICATIONS'),'Azkar Android 13 notification permission missing');
assert(activity.includes('MIN_INTERVAL_MINUTES = 5'),'Azkar native activity must honor the visible five-minute interval');
assert(activity.includes('AzkarReminderScheduler.stop(this)'),'Azkar native stop action must map directly to the scheduler');
assert(activity.includes('requestPermissionThenStart();'),'Azkar native start action must proceed directly from the authenticated toggle');
assert(azScheduler.includes('MIN_INTERVAL_MINUTES = 5'),'Azkar scheduler must honor five-minute reminders');
assert(azScheduler.includes('setAndAllowWhileIdle'),'Azkar reminders must remain locally scheduled while the app UI is closed');
assert(azScheduler.includes('PendingIntent.getBroadcast')&&azScheduler.includes('AzkarReminderReceiver.class'),'Azkar reminder must be delivered by BroadcastReceiver without an open TWA page');
assert(azReceiver.includes('POST_NOTIFICATIONS')&&azReceiver.includes('AzkarReminderScheduler.stop(context)'),'revoked notification permission must stop stale Azkar wakeups');
assert(azReceiver.includes('R.raw.azkar_subhanallah')&&!azReceiver.includes('getIdentifier'),'Azkar voice files must be statically retained in release resources');
const prayerRequired=['prayer_channel_adhan','prayer_channel_notice','prayer_channel_description','prayer_notification_title','prayer_notification_now','prayer_notification_advance','prayer_playback_stop','prayer_notification_permission_required','prayer_exact_alarm_hint','prayer_name_fajr','prayer_name_dhuhr','prayer_name_asr','prayer_name_maghrib','prayer_name_isha'];
const widgetRequired=['widget_app_name','widget_city_unavailable','widget_refresh_required','widget_value_unavailable','widget_qibla_unavailable','widget_qibla_value'];
for(const set of sets){let p=`android-twa/native/prayer-widget/res/${set}/strings.xml`;assert(fs.existsSync(p),`${p} missing`);let n=stringNames(read(p));for(const k of prayerRequired)assert(n.has(k),`${set} missing ${k}`);p=`android-twa/native/widget/res/${set}/strings.xml`;n=stringNames(read(p));for(const k of widgetRequired)assert(n.has(k),`${set} missing ${k}`);}
const token=read('android-twa/native/prayer-widget/NativeBridgeToken.java');
const earlyBootstrap=read('js/native-bridge-bootstrap.js');
const indexHtml=read('index.html');
const launcher=read('android-twa/native/prayer-widget/QiblaLauncherActivity.java');
const sync=read('android-twa/native/prayer-widget/PrayerWidgetSyncActivity.java');
const scheduler=read('android-twa/native/prayer-widget/PrayerNativeScheduler.java');
const receiver=read('android-twa/native/prayer-widget/PrayerNotificationReceiver.java');
const adhanService=read('android-twa/native/prayer-widget/AdhanPlaybackService.java');
const prayerBoot=read('android-twa/native/prayer-widget/PrayerBootReceiver.java');
const widgetRefresh=read('android-twa/native/prayer-widget/PrayerWidgetRefreshReceiver.java');
const widget=read('android-twa/native/widget/QiblaWidgetProvider.java');
const apply=read('android-twa/apply_native_widget.ps1');
for(const t of ['SecureRandom','MODE_PRIVATE','candidate'])assert(token.includes(t),`token gate missing ${t}`);
assert(launcher.includes('.fragment("nativeToken="'),'native token must be put in URL fragment');
assert(!launcher.includes('appendQueryParameter("nativeToken"'),'native token must never enter HTTP query');
assert(earlyBootstrap.includes("sessionStorage.setItem('qiblaastro:native-token',token)")&&earlyBootstrap.includes("params.delete('nativeToken')"),'native token must be captured and stripped before external scripts initialize');
assert(indexHtml.indexOf('native-bridge-bootstrap.js')<indexHtml.indexOf('googletagmanager.com'),'native token stripping must run before analytics is loaded');
assert(sync.includes('NativeBridgeToken.valid'),'sync activity must reject unauthenticated data');
assert(sync.includes('MODE_PRIVATE'),'sync data must use app-private storage');
assert(sync.includes('safePlan(d.getQueryParameter("plan"))'),'native prayer bridge must validate the date-stamped plan before storing it');
assert(sync.includes('widgetOnly="1".equals')&&sync.includes('if(widgetOnly){finish();return;}'),'widget-only refresh must not trigger notification or exact-alarm permission UI');
assert(sync.includes('if(!widgetOnly)e.putString("mode_"+id'),'widget-only refresh must preserve existing Adhan delivery choices');
assert(sync.includes('days.length<2||days.length>14'),'native prayer bridge must bound the background plan horizon');
assert(scheduler.includes('setExactAndAllowWhileIdle')&&scheduler.includes('canScheduleExactAlarms'),'actual prayer scheduling must use user-granted exact alarms');
assert(scheduler.includes('setAndAllowWhileIdle'),'pre-prayer and no-special-access fallback must remain idle-safe');
assert(scheduler.includes('catch (SecurityException ignored)'),'exact-alarm permission races must fall back without crashing delivery');
assert(scheduler.includes('BACKUP_REQ')&&scheduler.includes('PRAYER_NATIVE_BACKUP_'),'revoking exact-alarm access must leave an approximate prayer backup');
assert(scheduler.includes('AlarmManager.RTC_WAKEUP'),'prayer alarm must be able to wake delivery while the app UI is closed');
assert(scheduler.includes('PendingIntent.getBroadcast')&&scheduler.includes('PrayerNotificationReceiver.class'),'prayer alarm must target a BroadcastReceiver rather than an open Activity/page');
assert(scheduler.includes('PRE_REQ')&&scheduler.includes('boolean pre'),'pre-prayer alert must be separate from prayer-time event');
assert(scheduler.includes('KEY_PLAN = "plan_v1"'),'date-stamped native prayer plan store is missing');
assert(scheduler.includes('nextPlannedOccurrence(plan, i, now, tz)'),'native scheduler must select the next dated prayer instead of repeating stale daily minutes');
assert(scheduler.includes('if (actual <= 0L) continue;'),'an exhausted date-stamped plan must fail closed instead of replaying stale times');
assert(receiver.includes('extends BroadcastReceiver'),'prayer delivery must remain an Android BroadcastReceiver independent of the TWA lifecycle');
assert(receiver.includes('AdhanPlaybackService.ACTION_PLAY')&&receiver.includes('PrayerNativeScheduler.reschedule(context);'),'receiver must start native Adhan playback and then schedule the next dated event');
assert(receiver.includes('last_delivery_')&&receiver.includes('scheduledAt'),'exact and backup alarms must be deduplicated before playback');
assert(prayerBoot.includes('ACTION_BOOT_COMPLETED')&&prayerBoot.includes('ACTION_MY_PACKAGE_REPLACED')&&prayerBoot.includes('ACTION_TIMEZONE_CHANGED')&&prayerBoot.includes('ACTION_TIME_CHANGED'),'prayer alarms must be restored after reboot/app replacement/time changes');
assert(prayerBoot.includes('PrayerNativeScheduler.reschedule(context)'),'boot/time receiver must restore the native prayer schedule');
for(const raw of ['adhan_mecca.mp3','adhan_ahmed_al_nufais.mp3','adhan_islam_sobhi.mp3','adhan_fajr.mp3'])assert(apply.includes(raw),`native Adhan package missing ${raw}`);
for(const token of ['extends Service','startForeground','MediaPlayer','USAGE_ALARM','AudioFocusRequest','setWakeMode','START_NOT_STICKY','ACTION_STOP'])assert(adhanService.includes(token),`native foreground Adhan service missing ${token}`);
for(const raw of ['R.raw.adhan_mecca','R.raw.adhan_ahmed_al_nufais','R.raw.adhan_islam_sobhi','R.raw.adhan_fajr'])assert(adhanService.includes(raw),`native Adhan resource must survive release resource shrinking: ${raw}`);
assert(!adhanService.includes('http://')&&!adhanService.includes('https://')&&!adhanService.includes('MediaRecorder'),'Adhan service must remain bundled playback-only');
assert(widget.includes('PrayerNativeScheduler.PREFS'),'widget must read authenticated app-private prayer store');
assert(widget.includes('PrayerNativeScheduler.nextPrayer')&&widget.includes('PrayerWidgetRefreshReceiver.schedule'),'widget must use dated local plan and event-driven refresh');
assert(widgetRefresh.includes('setAndAllowWhileIdle')&&widgetRefresh.includes('ids.length == 0'),'widget refresh must run only for installed widgets at the next prayer boundary');
assert(!/android:name=["'](?:com\.qiblalabs\.)?WidgetDataActivity["']/.test(apply),'legacy WidgetDataActivity component must remain absent');
assert(apply.includes('QiblaWidgetProvider')&&apply.includes('PrayerWidgetSyncActivity'),'authenticated widget integration missing');
const plan=read('js/presentation/prayer/native-plan.js');
assert(plan.includes('QiblaPrayerMethods.calculate'),'background plan must reuse the approved prayer method engine rather than duplicate its equations');
assert(plan.includes('QiblaPrayerLocation.dateKey'),'background plan must use the effective prayer-location timezone date');
assert(plan.includes("typeof runtime.getSchedule==='function'"),'background plan must prefer the authoritative advanced prayer schedule');
assert(plan.includes('sameMinutes(first.times,current)'),'background plan must match the live displayed schedule before it can cross the native bridge');
assert(plan.includes('Math.min(14'),'background plan horizon must remain bounded');
const webSync=read('js/presentation/prayer/schedule-sync.js');
assert(webSync.includes("TOKEN_KEY='qiblaastro:native-token'"),'web sync token storage missing');
assert(webSync.includes("typeof runtime.getSchedule==='function'"),'native schedule sync must prefer the authoritative advanced prayer schedule');
assert(webSync.includes("AUTO_KEY='qiblaastro:prayer-native-sync-enabled:v1'"),'native prayer sync activation marker missing');
assert(webSync.includes("LAST_SYNC_KEY='qiblaastro:prayer-native-sync-last:v1'"),'native prayer sync de-duplication marker missing');
assert(webSync.includes('root.location.hash'),'web bridge must capture token from non-HTTP fragment');
assert(webSync.includes('intent://prayer-sync?'),'web prayer sync intent missing');
assert(webSync.includes("q.set('plan',payload.planText)"),'web prayer bridge must send the validated date-stamped plan');
assert(webSync.includes("q.set('widgetOnly','1')")&&webSync.includes('syncWidget:widgetSync'),'TWA must expose an explicit widget-only refresh without enabling Adhan');
assert(webSync.includes("q.set('notify',st.enabled?'1':'0')"),'every native handoff must carry the real Adhan master state so legacy Code 3 cannot misread widget-only sync as a disable command');
assert(!webSync.includes("q.set('notify',widgetOnly?'0':"),'widget-only sync must never synthesize notify=0 for legacy Code 3');
assert(webSync.includes("WIDGET_AUTO_KEY='qiblaastro:widget-native-sync-enabled:v1'")&&webSync.includes('if(launched)setWidgetAutoEnabled()'),'widget auto-refresh marker must activate only after a successful explicit widget refresh');
assert(webSync.includes('var AUTO_NATIVE_NAVIGATION=false'),'passive Android intent navigation must remain disabled during startup, focus, polling and visibility events');
assert(webSync.includes("return nativeSync(reason||'widget-auto',true)"),'the widget-only sync path must remain available for an explicit/future guarded invocation');
assert(!/setTimeout\(function\(\)\{explicitSync\(\);?\},800\)/.test(webSync),'startup must never trigger delivery permissions through explicitSync');
assert(webSync.includes('QiblaPrayerNativePlan.build(14)'),'web prayer bridge must keep two weeks of dated prayer times available while the TWA is closed');
assert(webSync.includes("reason==='explicit'"),'native prayer sync must distinguish explicit user activation from automatic refresh');
assert(webSync.includes("maybeNativeSync('startup')"),'startup may reevaluate sync state but AUTO_NATIVE_NAVIGATION must keep passive Android navigation blocked');
assert(webSync.includes("maybeNativeSync('location-changed')"),'trusted location changes may reevaluate sync state without bypassing the passive-navigation block');
assert(webSync.includes("maybeNativeSync('runtime-ready')"),'runtime readiness may reevaluate sync state without bypassing the passive-navigation block');
assert(webSync.includes('if(minute<0)return null'),'native prayer sync must fail closed until all five prayer times exist');
const azWeb=read('js/azkar-native-reminders.js');
const azPage=read('pages/azkar.html');
const azHost=read('js/presentation/azkar/host.js');
assert(azWeb.includes("token='+encodeURIComponent(token)"),'Azkar web bridge must send authenticated token');
assert(azWeb.includes('tokenFromHash'),'Azkar bridge must read token from fragment');
assert(azWeb.includes('tokenFromStorage'),'Azkar bridge must recover the authenticated token from the same-origin TWA session');
assert(azWeb.includes('Math.max(5,n)'),'Azkar web bridge must honor the visible five-minute interval');
const azLaunchIndex=azWeb.indexOf("var launched=launch('start'");
const azWriteIndex=azWeb.indexOf('writeState(state);',azLaunchIndex);
assert(azLaunchIndex>=0,'Azkar UI must inspect native launch result before persisting running state');
assert(azWeb.includes('if(!launched){clearStaleState();return;}'),'Azkar UI must fail closed without showing a false Android error note');
assert(azWriteIndex>azLaunchIndex,'Azkar UI must not persist a running native reminder before attempting Android launch');
assert(azWeb.includes('writeState(state);saveAudioSelection(state);setUi(true,state);'),'Azkar UI must persist the selected phrase/interval before rendering the successful running state');
assert(azWeb.includes("'intent://azkar-reminder?token='"),'Azkar bridge must use a package-scoped Android intent');
assert(azWeb.includes('topWin.location.href=uri'),'Azkar custom-scheme handoff must remain synchronous in the trusted user click');
assert(azWeb.includes('package=com.qiblalabs'),'Azkar intent must be locked to the confirmed Android package');
assert(azWeb.includes('category=android.intent.category.BROWSABLE'),'Azkar fallback intent must explicitly remain browser-invokable');
assert(!azWeb.includes("'qiblaastro://azkar-reminder?token='"),'unscoped custom-scheme token handoff must not return');
assert(!azWeb.includes('a.click()'),'Azkar native handoff must not rely on a synthetic hidden-anchor click');
assert(!azWeb.includes('تعذر بدء تنبيه Android')&&!azWeb.includes('افتح التطبيق من نسخة Android'),'obsolete visible Android failure note must remain removed');
assert(azHost.includes("TOKEN_KEY='qiblaastro:native-token'")&&azHost.includes("'?twa=1'")&&azHost.includes("'#nativeToken='+encodeURIComponent(token)"),'Azkar iframe host must propagate authenticated TWA context into the standalone page');
assert(azHost.includes('seedFrameContext(frame)'),'Azkar iframe must receive same-origin session TWA/token context after load');
assert(azPage.includes('#azAudio .az-audio-status{display:none!important}'),'Azkar audio status note must remain hidden; the toggle is the visible state control');
assert(azPage.includes('azkar-native-reminders.js?v=20260829-selection1'),'Azkar page must load the current trusted package-scoped native reminder bridge with selection persistence');
const bootstrap=read('js/presentation/bootstrap.js');
assert(bootstrap.includes('schedule-sync.js?v=20260829-widget-clean12'),'authenticated widget/prayer sync loader version missing');
assert(webSync.includes('native-plan.js?v=20260827-authoritative1'),'authenticated dated-plan loader version missing');
const sw=read('service-worker.js');
assert(/qiblaastro-v\d+\.\d+-/.test(sw),'versioned service-worker cache missing');
assert(sw.includes('qiblaastro-v5.74-native-adhan-owner-20260829'),'current Code 5 offline/Adhan/Azkar service-worker version missing');
assert(sw.includes('./js/presentation/prayer/native-plan.js')&&sw.includes('./js/presentation/prayer/schedule-sync.js')&&sw.includes('./js/azkar-native-reminders.js'),'native web bridge files must remain in critical offline cache');
console.log('Native Android localization/security gate: PASS');
console.log('Prayer actual-time + separate pre-alert + local Adhan audio: PASS');
console.log('Prayer CLOSED-APP native chain (exact RTC_WAKEUP -> BroadcastReceiver -> foreground local Adhan -> reschedule): PASS');
console.log('Prayer reboot/app-replacement/time-change schedule restoration: PASS');
console.log('Prayer passive Android navigation blocked; explicit authenticated sync remains available: PASS');
console.log('Prayer native bridge carries a validated 14-day date-stamped schedule and never replays an exhausted plan: PASS');
console.log('Azkar iframe token propagation + package-scoped user-gesture handoff: PASS');
console.log('Azkar native toggle + five-minute local background scheduling + selection persistence: PASS');
console.log('Prayer notifications AR/EN/FR/ID/UR: PASS');
console.log('Widget AR/EN/FR/ID/UR: PASS');
console.log('Per-install fragment token + MODE_PRIVATE store; legacy WidgetDataActivity absent: PASS');
